<?php
function handle_action(array $u): void {
 global $db;
 check_csrf(); $action=$_POST['action']??''; $role=$u['role']; $id=(int)($_POST['id']??0);
 $allowed=['profile'=>['customer','admin','rider'],'read'=>['customer','admin','rider'],'address'=>['customer'],'address_delete'=>['customer'],'order'=>['customer'],'subscription'=>['customer'],'subscription_status'=>['customer'],'reference'=>['customer'],'feedback'=>['customer'],'cancel'=>['customer'],'status'=>['admin','rider'],'assign'=>['admin'],'payment'=>['admin'],'product'=>['admin'],'area'=>['admin'],'station'=>['admin'],'rider'=>['admin'],'availability'=>['rider'],'location'=>['rider']];
 $allowed['schedule']=['admin'];
 if(!in_array($role,$allowed[$action]??[],true)) throw new RuntimeException('Action not permitted.');
 $db->beginTransaction();
 try {
 switch($action){
 case 'profile': $name=trim($_POST['name']??''); if(!$name || strlen($name)>100) throw new RuntimeException('Enter a valid name.'); q('UPDATE users SET name=?,phone=? WHERE id=?',[$name,substr(trim($_POST['phone']??''),0,30),$u['id']]); if(!empty($_POST['password'])) { if(!password_verify($_POST['current_password']??'',$u['password']) || strlen($_POST['password'])<10) throw new RuntimeException('Verify your current password and use at least 10 characters.'); q('UPDATE users SET password=? WHERE id=?',[password_hash($_POST['password'],PASSWORD_DEFAULT),$u['id']]); } break;
 case 'read': q('UPDATE notifications SET read_at=NOW() WHERE user_id=?',[$u['id']]); break;
 case 'address': $address=trim($_POST['address']??''); if(!$address || !one('SELECT id FROM delivery_areas WHERE barangay=? AND active=1',[$_POST['barangay']??''])) throw new RuntimeException('Enter an address in an available area.'); $lat=$_POST['latitude']??''; $lng=$_POST['longitude']??''; if(($lat!=='' && (!is_numeric($lat)||abs((float)$lat)>90)) || ($lng!=='' && (!is_numeric($lng)||abs((float)$lng)>180))) throw new RuntimeException('Invalid coordinates.'); if($id){if(!one('SELECT id FROM addresses WHERE id=? AND customer_id=?',[$id,$u['id']]))throw new RuntimeException('Address not found.');q('UPDATE addresses SET address=?,barangay=?,latitude=?,longitude=? WHERE id=? AND customer_id=?',[$address,$_POST['barangay'],$lat===''?null:$lat,$lng===''?null:$lng,$id,$u['id']]);}else q('INSERT INTO addresses(customer_id,address,barangay,latitude,longitude) VALUES(?,?,?,?,?)',[$u['id'],$address,$_POST['barangay'],$lat===''?null:$lat,$lng===''?null:$lng]); break;
 case 'address_delete': if(one('SELECT id FROM subscriptions WHERE address_id=?',[$id]))throw new RuntimeException('Addresses linked to subscriptions must be retained. You can edit the address.'); q('DELETE FROM addresses WHERE id=? AND customer_id=?',[$id,$u['id']]); break;
 case 'order': $oid=create_order((int)$u['id'],(int)$_POST['product_id'],(int)$_POST['quantity'],(int)$_POST['address_id'],str_replace('T',' ',$_POST['scheduled_at']),$_POST['payment_method']); $_SESSION['new_order']=$oid; break;
 case 'subscription': $days=array_values(array_unique(array_map('intval',$_POST['days']??[]))); if(!$days || array_diff($days,range(1,7))) throw new RuntimeException('Select valid weekdays.'); $start=$_POST['start_date']??''; if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$start) || date('Y-m-d',strtotime($start))!==$start || $start<date('Y-m-d')) throw new RuntimeException('Choose a valid start date.'); $time=$_POST['preferred_time']??''; if(!preg_match('/^([01]\d|2[0-3]):[0-5]\d$/',$time)) throw new RuntimeException('Invalid delivery time.'); $qty=(int)$_POST['quantity']; if($qty<1||$qty>100 || !one('SELECT id FROM products WHERE id=? AND active=1',[(int)$_POST['product_id']]) || !one('SELECT id FROM addresses WHERE id=? AND customer_id=?',[(int)$_POST['address_id'],$u['id']]) || !in_array($_POST['payment_method'],['COD','GCash','Maya'],true)) throw new RuntimeException('Invalid subscription details.'); q('INSERT INTO subscriptions(customer_id,product_id,address_id,quantity,selected_days,preferred_time,payment_method,start_date,next_delivery_date) VALUES(?,?,?,?,?,?,?,?,?)',[$u['id'],$_POST['product_id'],$_POST['address_id'],$qty,implode(',',$days),$time,$_POST['payment_method'],$start,next_date($days,$start,true)]); break;
 case 'subscription_status': $s=one('SELECT * FROM subscriptions WHERE id=? AND customer_id=? FOR UPDATE',[$id,$u['id']]); $state=$_POST['status']; if(!$s || $s['status']==='Cancelled' || !in_array($state,['Active','Paused','Cancelled'],true)) throw new RuntimeException('Invalid subscription change.'); $next=next_date(array_map('intval',explode(',',$s['selected_days'])),max(date('Y-m-d'),$s['start_date']),true); q('UPDATE subscriptions SET status=?,next_delivery_date=? WHERE id=?',[$state,$next,$id]); break;
 case 'reference': $o=one('SELECT * FROM orders WHERE id=? AND customer_id=?',[$id,$u['id']]); $ref=trim($_POST['reference']??''); if(!$o || $o['payment_method']==='COD' || !$ref || strlen($ref)>100) throw new RuntimeException('Invalid payment reference.'); q("UPDATE payments SET payment_reference=? WHERE order_id=? AND payment_status IN ('Pending','Failed')",[$ref,$id]); break;
 case 'feedback': if(!one("SELECT id FROM orders WHERE id=? AND customer_id=? AND status='Delivered'",[$id,$u['id']]) || (int)$_POST['rating']<1 || (int)$_POST['rating']>5) throw new RuntimeException('Only completed orders can be rated.'); q('INSERT INTO feedback(order_id,customer_id,rating,comment) VALUES(?,?,?,?)',[$id,$u['id'],(int)$_POST['rating'],substr(trim($_POST['comment']??''),0,2000)]); break;
 case 'cancel': $o=one('SELECT * FROM orders WHERE id=? AND customer_id=? FOR UPDATE',[$id,$u['id']]); if(!$o || $o['status']!=='Pending') throw new RuntimeException('Only pending orders can be cancelled.'); q("UPDATE orders SET status='Cancelled' WHERE id=?",[$id]); q('INSERT INTO order_status_history(order_id,actor_id,status) VALUES(?,?,?)',[$id,$u['id'],'Cancelled']); notify((int)$u['id'],'Your order was cancelled.'); break;
 case 'assign': $o=one('SELECT * FROM orders WHERE id=? FOR UPDATE',[$id]); $r=one("SELECT * FROM riders WHERE user_id=? AND availability<>'Offline'",[(int)$_POST['rider_id']]); if(!$o || !$r || !in_array($o['status'],['Confirmed','Preparing','Assigned'],true)) throw new RuntimeException('Confirm the order and select an available rider.'); q("UPDATE orders SET rider_id=?,status='Assigned' WHERE id=?",[$r['user_id'],$id]); q('INSERT INTO order_status_history(order_id,actor_id,status) VALUES(?,?,?)',[$id,$u['id'],'Assigned']); notify((int)$o['customer_id'],'A rider has been assigned to '.$o['order_number']); break;
 case 'status': $o=one('SELECT * FROM orders WHERE id=? FOR UPDATE',[$id]); if(!$o || ($role==='rider' && (int)$o['rider_id']!==(int)$u['id'])) throw new RuntimeException('Delivery not assigned to you.'); $state=$_POST['status']; if($state==='Picked Up'){ if($role!=='rider' || $o['status']!=='Assigned') throw new RuntimeException('Pickup is available for assigned orders.'); q('UPDATE orders SET picked_up_at=NOW() WHERE id=?',[$id]); q('INSERT INTO order_status_history(order_id,actor_id,status,note) VALUES(?,?,?,?)',[$id,$u['id'],'Assigned','Picked up from station']); break; } $trans=['Pending'=>['Confirmed','Cancelled'],'Confirmed'=>['Preparing','Cancelled'],'Preparing'=>['Cancelled'],'Assigned'=>['Out for Delivery','Cancelled'],'Out for Delivery'=>['Delivered']]; if(!in_array($state,$trans[$o['status']]??[],true) || ($role==='rider' && !in_array($state,['Out for Delivery','Delivered'],true))) throw new RuntimeException('Invalid status transition.'); if($state==='Out for Delivery' && !$o['picked_up_at']) throw new RuntimeException('Mark the order picked up first.'); q('UPDATE orders SET status=?,delivered_at=IF(?=?,NOW(),delivered_at) WHERE id=?',[$state,$state,'Delivered',$id]); if($state==='Delivered' && $o['payment_method']==='COD') q("UPDATE payments SET payment_status='Paid',paid_at=NOW() WHERE order_id=?",[$id]); q('INSERT INTO order_status_history(order_id,actor_id,status) VALUES(?,?,?)',[$id,$u['id'],$state]); notify((int)$o['customer_id'],"Your order {$o['order_number']} is now $state."); break;
 case 'schedule': $o=one('SELECT * FROM orders WHERE id=? FOR UPDATE',[$id]);$date=str_replace('T',' ',$_POST['scheduled_at']??'');$parsed=DateTimeImmutable::createFromFormat('!Y-m-d H:i',$date);if(!$o || !in_array($o['status'],['Pending','Confirmed','Preparing','Assigned'],true)||!$parsed||$parsed->format('Y-m-d H:i')!==$date||$parsed->getTimestamp()<time())throw new RuntimeException('Choose a future time for an order awaiting delivery.');q('UPDATE orders SET scheduled_at=? WHERE id=?',[$date,$id]);q('INSERT INTO order_status_history(order_id,actor_id,status,note) VALUES(?,?,?,?)',[$id,$u['id'],$o['status'],'Rescheduled to '.$date]);notify((int)$o['customer_id'],'Your delivery '.$o['order_number'].' has been rescheduled to '.$date.'.');break;
 case 'payment': $state=$_POST['payment_status']; if(!in_array($state,['Pending','Paid','Failed','Refunded'],true)) throw new RuntimeException('Invalid payment status.'); q('UPDATE payments SET payment_status=?,paid_at=IF(?=?,NOW(),NULL) WHERE order_id=?',[$state,$state,'Paid',$id]); break;
 case 'product': $name=trim($_POST['name']??''); $price=filter_var($_POST['price']??'',FILTER_VALIDATE_FLOAT); if(!$name || $price===false || $price<=0) throw new RuntimeException('Enter a product name and positive price.'); if($id) q('UPDATE products SET name=?,description=?,price=?,active=? WHERE id=?',[$name,$_POST['description']??'',$price,isset($_POST['active'])?1:0,$id]); else q('INSERT INTO products(station_id,name,description,price) VALUES(1,?,?,?)',[$name,$_POST['description']??'',$price]); break;
 case 'area': $name=trim($_POST['barangay']??''); $fee=filter_var($_POST['fee']??'',FILTER_VALIDATE_FLOAT); if(!$name || $fee===false || $fee<0) throw new RuntimeException('Enter a barangay and nonnegative fee.'); if($id) q('UPDATE delivery_areas SET barangay=?,fee=?,active=? WHERE id=?',[$name,$fee,isset($_POST['active'])?1:0,$id]); else q('INSERT INTO delivery_areas(station_id,barangay,fee) VALUES(1,?,?)',[$name,$fee]); break;
 case 'station': if(!trim($_POST['name']??'')) throw new RuntimeException('Station name is required.'); q('UPDATE water_stations SET name=?,address=?,phone=?,payment_instructions=? WHERE id=1',[$_POST['name'],$_POST['address'],$_POST['phone'],$_POST['payment_instructions']]); break;
 case 'rider': if(!filter_var($_POST['email'],FILTER_VALIDATE_EMAIL)||strlen($_POST['password'])<10||!trim($_POST['name'])) throw new RuntimeException('Provide a name, valid email and password of at least 10 characters.'); q("INSERT INTO users(name,email,password,role,phone) VALUES(?,?,?,'rider',?)",[$_POST['name'],$_POST['email'],password_hash($_POST['password'],PASSWORD_DEFAULT),$_POST['phone']]); q('INSERT INTO riders(user_id,station_id) VALUES(?,1)',[$db->lastInsertId()]); break;
 case 'availability': if(!in_array($_POST['availability'],['Available','Busy','Offline'],true)) throw new RuntimeException('Invalid availability.'); q('UPDATE riders SET availability=? WHERE user_id=?',[$_POST['availability'],$u['id']]); break;
 case 'location': if(!one("SELECT id FROM orders WHERE rider_id=? AND status IN ('Assigned','Out for Delivery')",[$u['id']])) throw new RuntimeException('An active delivery is required to share location.'); if(!is_numeric($_POST['latitude']??null)||!is_numeric($_POST['longitude']??null)||abs((float)$_POST['latitude'])>90||abs((float)$_POST['longitude'])>180) throw new RuntimeException('Invalid location.'); q('INSERT INTO rider_locations(rider_id,latitude,longitude) VALUES(?,?,?) ON DUPLICATE KEY UPDATE latitude=VALUES(latitude),longitude=VALUES(longitude),updated_at=NOW()',[$u['id'],$_POST['latitude'],$_POST['longitude']]); break;
 }
 $db->commit();
 } catch(Throwable $ex){ $db->rollBack(); throw $ex; }
}
