<?php
declare(strict_types=1);
date_default_timezone_set('Asia/Manila');
$config=require __DIR__.'/config.php';
if(PHP_SAPI!=='cli') { session_set_cookie_params(['httponly'=>true,'secure'=>!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS']!=='off','samesite'=>'Lax']); session_start(); }
try { $db=new PDO("mysql:host={$config['host']};port={$config['port']};dbname={$config['database']};charset=utf8mb4",$config['username'],$config['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]); $db->exec("SET time_zone = '+08:00'"); } catch(PDOException $e) { http_response_code(503); exit('Database unavailable. Import aquasync_db.sql and check app/config.php.'); }
function q(string $sql,array $params=[]): PDOStatement { global $db; $s=$db->prepare($sql); $s->execute($params); return $s; }
function rows(string $sql,array $params=[]): array { return q($sql,$params)->fetchAll(); }
function one(string $sql,array $params=[]): ?array { return q($sql,$params)->fetch() ?: null; }
function e($v): string { return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8'); }
function url(string $path=''): string { global $config; return $config['base'].'/'.$path; }
function go(string $path): never { header('Location: '.url($path)); exit; }
function user(): ?array { return isset($_SESSION['uid']) ? one('SELECT * FROM users WHERE id=?',[$_SESSION['uid']]) : null; }
function require_role(string $role): array { $u=user(); if(!$u) go('login.php'); if($u['role']!==$role) { http_response_code(403); exit('Access denied'); } return $u; }
function csrf(): string { $_SESSION['csrf']??=bin2hex(random_bytes(32)); return '<input type="hidden" name="csrf" value="'.e($_SESSION['csrf']).'">'; }
function check_csrf(): void { if(!hash_equals($_SESSION['csrf']??'',(string)($_POST['csrf']??'')) || empty($_SESSION['csrf'])) { http_response_code(403); exit('Invalid request token'); } }
function notify(int $uid,string $message,?string $key=null): void { q('INSERT IGNORE INTO notifications(user_id,message,dedupe_key) VALUES(?,?,?)',[$uid,$message,$key]); }
function money($v): string { return '₱'.number_format((float)$v,2); }
function prediction(int $uid): ?array { $dates=rows('SELECT DATE(delivered_at) d FROM orders WHERE customer_id=? AND status=? GROUP BY DATE(delivered_at) ORDER BY d DESC LIMIT 10',[$uid,'Delivered']); if(count($dates)<2) return null; $interval=(strtotime($dates[0]['d'])-strtotime($dates[count($dates)-1]['d']))/86400/(count($dates)-1); return ['days'=>round($interval,1),'date'=>date('Y-m-d',strtotime($dates[0]['d'].' +'.max(1,(int)round($interval)).' days'))]; }
function next_date(array $days,string $from,bool $inclusive=false): string { for($i=$inclusive?0:1;$i<9;$i++){ $d=date('Y-m-d',strtotime($from." +$i days")); if(in_array((int)date('N',strtotime($d)),$days,true)) return $d; } throw new RuntimeException('Select delivery days.'); }
function haversine(float $a,float $b,float $c,float $d): float { $x=sin(deg2rad($c-$a)/2)**2+cos(deg2rad($a))*cos(deg2rad($c))*sin(deg2rad($d-$b)/2)**2; return 6371*2*asin(sqrt(min(1,$x))); }
function create_order(int $uid,int $pid,int $qty,int $aid,string $date,string $method,?int $sid=null,?string $sdate=null): int { global $db; $p=one('SELECT * FROM products WHERE id=? AND active=1',[$pid]); $a=one('SELECT * FROM addresses WHERE id=? AND customer_id=?',[$aid,$uid]); if(!$p || !$a || $qty<1 || $qty>100 || !in_array($method,['COD','GCash','Maya'],true)) throw new RuntimeException('Invalid order details.'); $parsed=DateTimeImmutable::createFromFormat('!Y-m-d H:i',$date); if(!$parsed || $parsed->format('Y-m-d H:i')!==$date || (!$sid && $parsed->getTimestamp()<time())) throw new RuntimeException('Choose a future delivery date and time.'); $area=one('SELECT * FROM delivery_areas WHERE barangay=? AND active=1',[$a['barangay']]); if(!$area) throw new RuntimeException('This delivery area is unavailable.'); $total=$p['price']*$qty+$area['fee']; q('INSERT INTO orders(customer_id,station_id,subscription_id,subscription_date,quantity,gallon_price,delivery_fee,total,address,barangay,latitude,longitude,payment_method,scheduled_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)',[$uid,1,$sid,$sdate,$qty,$p['price'],$area['fee'],$total,$a['address'],$a['barangay'],$a['latitude'],$a['longitude'],$method,$date]); $id=(int)$db->lastInsertId(); $number='AQ-'.date('Ymd').'-'.str_pad((string)$id,4,'0',STR_PAD_LEFT); q('UPDATE orders SET order_number=? WHERE id=?',[$number,$id]); q('INSERT INTO order_items(order_id,product_id,quantity,unit_price) VALUES(?,?,?,?)',[$id,$pid,$qty,$p['price']]); q('INSERT INTO payments(order_id,payment_method,amount) VALUES(?,?,?)',[$id,$method,$total]); q('INSERT INTO order_status_history(order_id,actor_id,status) VALUES(?,?,?)',[$id,$uid,'Pending']); notify($uid,"Order $number was placed and is awaiting confirmation."); return $id; }
