<?php
function field(string $name,string $label,string $type='text',$value='',bool $required=true): void { echo '<div class="mb-3"><label class="form-label">'.e($label).'</label><input class="form-control" name="'.e($name).'" type="'.e($type).'" value="'.e($value).'" '.($type==='number'?'step="any" ':'').($required?'required':'').'></div>'; }
function select_field(string $name,string $label,array $options,$selected=''): void { echo '<div class="mb-3"><label class="form-label">'.e($label).'</label><select class="form-select" name="'.e($name).'" '.(array_key_exists('',$options)?'':'required').'>'; foreach($options as $key=>$label) echo '<option value="'.e($key).'" '.((string)$key===(string)$selected?'selected':'').'>'.e($label).'</option>'; echo '</select></div>'; }
function form_start(string $action,int $id=0,string $confirm=''): void { echo '<form method="post" '.($confirm?'data-confirm="'.e($confirm).'"':'').'>'.csrf().'<input type="hidden" name="action" value="'.e($action).'"><input type="hidden" name="id" value="'.$id.'">'; }
function form_end(string $label='Save changes'): void { $icon=str_contains(strtolower($label),'cancel')||str_contains(strtolower($label),'delete')?'x-circle':(str_contains(strtolower($label),'delivery')?'truck':(str_contains(strtolower($label),'create')||str_contains(strtolower($label),'add')?'plus-circle':'check2-circle')); echo '<button class="btn btn-primary"><i class="bi bi-'.$icon.'" aria-hidden="true"></i>'.e($label).'</button></form>'; }
function start_page(array $u,string $page): void { $nav=$u['role']==='admin'?['dashboard'=>'grid','orders'=>'bag','deliveries'=>'truck','customers'=>'people','subscriptions'=>'calendar-week','riders'=>'bicycle','products'=>'droplet','areas'=>'geo-alt','reports'=>'bar-chart','feedback'=>'star','notifications'=>'bell','settings'=>'gear']:($u['role']==='customer'?['dashboard'=>'grid','order'=>'droplet','orders'=>'bag','subscriptions'=>'calendar-week','addresses'=>'geo-alt','notifications'=>'bell','profile'=>'person']:['dashboard'=>'grid','deliveries'=>'truck','completed'=>'check-circle','notifications'=>'bell','profile'=>'person']); $count=one('SELECT COUNT(*) n FROM notifications WHERE user_id=? AND read_at IS NULL',[$u['id']])['n']; ?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#103a50"><title><?=e(ucfirst($page))?> · AquaSync</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet"><link href="<?=url('assets/style.css')?>" rel="stylesheet"><link href="<?=url('assets/theme.css')?>" rel="stylesheet"></head><body><div class="sidebar-overlay" aria-hidden="true"></div><aside class="sidebar" id="workspace-nav"><a class="brand" href="<?=url($u['role'].'/')?>"><i class="bi bi-droplet-fill" aria-hidden="true"></i> AquaSync</a><div class="role-label muted mt-2 small"><?=e($u['role']==='admin'?'Station workspace':ucfirst($u['role']).' portal')?></div><small>Workspace</small><nav class="nav flex-column" aria-label="Main navigation"><?php foreach($nav as $p=>$icon): ?><a class="nav-link <?=$page===$p?'active':''?>" <?=$page===$p?'aria-current="page"':''?> href="?page=<?=$p?>"><i class="bi bi-<?=$icon?>" aria-hidden="true"></i><?=e($p==='areas'?'Delivery Areas':ucfirst($p))?></a><?php endforeach; ?></nav><div class="sidebar-footer"><div class="station-note"><i class="bi bi-droplet-half" aria-hidden="true"></i><div><strong>Fresh water, on time.</strong>Your everyday refill companion</div></div><form method="post" action="<?=url('logout.php')?>"><?=csrf()?><button class="btn text-muted logout-button"><i class="bi bi-box-arrow-right" aria-hidden="true"></i>Logout</button></form></div></aside><main class="main"><div class="topbar"><div class="breadcrumbs"><button type="button" class="mobile-toggle" aria-label="Open navigation" aria-controls="workspace-nav" aria-expanded="false"><i class="bi bi-list" aria-hidden="true"></i></button><i class="bi bi-house-door muted" aria-hidden="true"></i><span class="muted workspace-label">Workspace</span><i class="bi bi-chevron-right muted" aria-hidden="true"></i><strong><?=e($page==='areas'?'Delivery areas':ucfirst($page))?></strong></div><div class="account-menu"><a class="notification-button" href="?page=notifications" aria-label="Notifications, <?=(int)$count?> unread"><i class="bi bi-bell" aria-hidden="true"></i><?php if($count):?><span class="notification-count"><?=(int)$count>99?'99+':(int)$count?></span><?php endif;?></a><div class="account-details"><div class="account-name"><?=e($u['name'])?></div><div class="account-role"><?=e($u['role']==='admin'?'Station administrator':$u['role'])?></div></div><a class="avatar" href="?page=<?=$u['role']==='admin'?'settings':'profile'?>" aria-label="Your account"><?=e(strtoupper(substr($u['name'],0,1)))?></a></div></div><?php }
function end_page(): void { echo '<footer class="main-footer"><span><i class="bi bi-droplet-fill" aria-hidden="true"></i>AquaSync · Fresh water. Right on schedule.</span><span>Local water delivery, made simple</span></footer></main><script src="'.url('assets/app.js').'"></script></body></html>'; }
function stat_card(string $label,$value,string $icon): void { echo '<div class="col-sm-6 col-xl-3"><div class="card stat-card"><div class="card-body"><i class="stat-icon bi bi-'.e($icon).'" aria-hidden="true"></i><span class="stat-label">'.e($label).'</span><div class="stat-value '.(strlen((string)$value)>14?'long-value':'').'">'.e($value).'</div></div></div></div>'; }
function orders_table(array $orders): void { echo '<div class="card"><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Order</th><th>Customer / Area</th><th>Delivery</th><th>Total</th><th>Status</th></tr></thead><tbody>'; foreach($orders as $o) echo '<tr><td><a class="fw-bold text-decoration-none" href="?page=detail&id='.$o['id'].'">'.e($o['order_number']).'</a><div class="muted small">'.$o['quantity'].' gallon(s)</div></td><td>'.e($o['customer_name']??'Your order').'<div class="muted small">'.e($o['barangay']).'</div></td><td>'.e(date('M j, g:i A',strtotime($o['scheduled_at']))).'</td><td>'.money($o['total']).'</td><td><span class="badge '.e($o['status']).'">'.e($o['status']).'</span></td></tr>'; if(!$orders) echo '<tr><td colspan="5" class="text-center muted py-5">No orders to display.</td></tr>'; echo '</tbody></table></div></div>'; }
function chart(string $title,array $data): void { echo '<div class="card"><div class="card-body"><h3 class="section-title">'.e($title).'</h3>'; $max=max(1,...array_map(fn($d)=>(float)$d['value'],$data)); foreach($data as $d) echo '<div class="chart-row"><span>'.e($d['label']).'</span><div class="flex-grow-1"><div class="bar" style="width:'.(100*(float)$d['value']/$max).'%"></div></div><b class="small">'.e($d['value']).'</b></div>'; if(!$data) echo '<p class="muted">No data for this period.</p>'; echo '</div></div>'; }
function rider_cards(array $orders): void {
 echo '<div class="row">';
 foreach($orders as $o){echo '<div class="col-lg-6"><div class="card"><div class="card-body"><div class="d-flex justify-content-between"><strong>'.e($o['order_number']).'</strong><span class="badge">'.e($o['status']).'</span></div><h3 class="h5 mt-3">'.e($o['customer_name']).'</h3><p><i class="bi bi-geo-alt me-2"></i>'.e($o['address']).'<br>'.e($o['barangay']).'</p><p><a href="tel:'.e($o['customer_phone']).'">'.e($o['customer_phone']).'</a></p><div class="bg-light p-3 rounded mb-3">'.$o['quantity'].' gallons · '.money($o['total']).'<br>'.e($o['payment_method']).' · '.e($o['payment_status']).'<br>Requested: '.e(date('M j, g:i A',strtotime($o['scheduled_at']))).'</div><a href="?page=detail&id='.$o['id'].'" class="btn btn-outline-info mb-3">View delivery / start</a>';
 $next=$o['status']==='Assigned'?($o['picked_up_at']?'Out for Delivery':'Picked Up'):($o['status']==='Out for Delivery'?'Delivered':null);
 if($next){form_start('status',(int)$o['id'],'Mark delivery '.$next.'?');echo '<input type="hidden" name="status" value="'.e($next).'">';form_end('Mark '.$next);}
 echo '</div></div></div>';}
 if(!$orders)echo '<p class="muted">No deliveries in this queue.</p>';echo '</div>';
}

