<?php
require __DIR__.'/bootstrap.php'; require __DIR__.'/actions.php'; require __DIR__.'/layout.php';
$u=require_role($requiredRole); $role=$u['role']; $page=$_GET['page']??'dashboard'; $id=(int)($_GET['id']??0); $error='';
if($_SERVER['REQUEST_METHOD']==='POST'){ try { handle_action($u); if(($_SERVER['HTTP_X_REQUESTED_WITH']??'')==='fetch') exit('Location updated successfully.'); $_SESSION['flash']='Changes saved successfully.'; if(isset($_SESSION['new_order'])){ $new=$_SESSION['new_order'];unset($_SESSION['new_order']); go($role.'/?page=detail&id='.$new); } go($role.'/?'.http_build_query($_GET)); }catch(Throwable $ex){ $error=$ex instanceof PDOException?'Unable to save. Check for duplicate entries or invalid details.':$ex->getMessage(); if(($_SERVER['HTTP_X_REQUESTED_WITH']??'')==='fetch'){http_response_code(422);exit($error);} } }
$scope=$role==='customer'?'o.customer_id=?':($role==='rider'?'o.rider_id=?':'1=1'); $params=$role==='admin'?[]:[$u['id']];
$orderSql='SELECT o.*,u.name customer_name,u.phone customer_phone,p.payment_status,p.payment_reference FROM orders o JOIN users u ON u.id=o.customer_id JOIN payments p ON p.order_id=o.id WHERE '.$scope;
start_page($u,$page); if($error) echo '<div class="alert alert-danger">'.e($error).'</div>'; if(isset($_SESSION['flash'])){echo '<div class="alert alert-success">'.e($_SESSION['flash']).'</div>';unset($_SESSION['flash']);}
if($page==='dashboard'){
 $pred=$role==='customer'?prediction((int)$u['id']):null;
 ?><div class="hero"><div class="small mb-2 text-uppercase" style="letter-spacing:2px"><?=date('l, F j, Y')?></div><h1 class="h2 fw-bold"><?=$role==='admin'?'A fresh start for every delivery.':($role==='rider'?'Ready for the road, '.e(explode(' ',$u['name'])[0]).'?':'Hello, '.e(explode(' ',$u['name'])[0]).' 👋')?></h1><p class="mb-4"><?=$role==='admin'?'Keep your station flowing. Manage orders, schedules and your delivery team.':($role==='rider'?'Your delivery queue and customer details, all in one place.':'Good water, one less thing to worry about. We’ve got your next refill covered.')?></p><a class="btn btn-light fw-semibold" href="?page=<?=$role==='customer'?'order':'deliveries'?>"><i class="bi bi-<?=$role==='customer'?'droplet':'truck'?> me-2"></i><?=$role==='customer'?'Order water':'View deliveries'?></a></div><div class="row"><?php
 if($role==='admin'){
 $s=one("SELECT SUM(DATE(created_at)=CURDATE()) today,SUM(status='Pending') pending,SUM(status='Out for Delivery') outgoing,SUM(status='Delivered' AND DATE(delivered_at)=CURDATE()) completed FROM orders"); stat_card("Today's Orders",$s['today']??0,'bag');stat_card('Pending Orders',$s['pending']??0,'hourglass');stat_card('Out for Delivery',$s['outgoing']??0,'truck');stat_card('Completed Today',$s['completed']??0,'check-circle');stat_card('Active Customers',one('SELECT COUNT(*) n FROM customers')['n'],'people');stat_card('Active Subscriptions',one("SELECT COUNT(*) n FROM subscriptions WHERE status='Active'")['n'],'calendar-week');stat_card('Available Riders',one("SELECT COUNT(*) n FROM riders WHERE availability='Available'")['n'],'bicycle');stat_card("Today's Revenue",money(one("SELECT COALESCE(SUM(amount),0) n FROM payments WHERE payment_status='Paid' AND DATE(paid_at)=CURDATE()")['n']),'cash');
 }elseif($role==='customer'){
 $next=one("SELECT MIN(next_delivery_date) d FROM subscriptions WHERE customer_id=? AND status='Active'",[$u['id']]);stat_card('Next Estimated Refill',$pred?date('M j',strtotime($pred['date'])):'Learning your rhythm','droplet');stat_card('Active Orders',one("SELECT COUNT(*) n FROM orders WHERE customer_id=? AND status NOT IN ('Delivered','Cancelled')",[$u['id']])['n'],'truck');stat_card('Next Scheduled Delivery',$next['d']?date('M j',strtotime($next['d'])):'No schedule','calendar-week');stat_card('Total Orders',one('SELECT COUNT(*) n FROM orders WHERE customer_id=?',[$u['id']])['n'],'bag');
 }else{stat_card("Today's Deliveries",one('SELECT COUNT(*) n FROM orders WHERE rider_id=? AND DATE(scheduled_at)=CURDATE()',[$u['id']])['n'],'truck');stat_card('In Your Queue',one("SELECT COUNT(*) n FROM orders WHERE rider_id=? AND status IN ('Assigned','Out for Delivery')",[$u['id']])['n'],'bag');stat_card('Completed Today',one("SELECT COUNT(*) n FROM orders WHERE rider_id=? AND DATE(delivered_at)=CURDATE() AND status='Delivered'",[$u['id']])['n'],'check-circle');stat_card('Availability',one('SELECT availability FROM riders WHERE user_id=?',[$u['id']])['availability'],'bicycle');}
 echo '</div>';
 if($role==='customer'){ ?><div class="row"><div class="col-lg-8"><h3 class="section-title">Current orders</h3><?php orders_table(rows($orderSql." AND o.status NOT IN ('Delivered','Cancelled') ORDER BY o.scheduled_at LIMIT 5",$params));?><h3 class="section-title">Recent orders</h3><?php orders_table(rows($orderSql.' ORDER BY o.created_at DESC LIMIT 5',$params));?></div><div class="col-lg-4"><div class="card"><div class="card-body"><i class="bi bi-droplet fs-2 text-info"></i><h3 class="section-title mt-3">Your refill rhythm</h3><p class="muted"><?=$pred?'Based on your recent orders, you may need another refill around '.e(date('F j',strtotime($pred['date']))).'. Your average interval is '.e($pred['days']).' days.':'Complete orders on at least two different days to estimate your next refill.'?></p><p class="small muted">This is an estimate based on order intervals. You can order anytime.</p><a class="btn btn-primary" href="?page=order">Order a refill</a></div></div><div class="card"><div class="card-body"><h3 class="section-title">Keep water on schedule</h3><p class="muted">Choose your weekdays and we’ll create recurring delivery orders.</p><a href="?page=subscriptions" class="btn btn-outline-info">Create schedule</a></div></div></div></div><?php
 }elseif($role==='admin'){?><div class="row"><div class="col-lg-8"><h3 class="section-title">Orders needing attention</h3><?php orders_table(rows($orderSql." AND o.status='Pending' ORDER BY o.scheduled_at LIMIT 6"));?><div class="row"><div class="col-md-6"><?php chart('Daily orders',rows("SELECT DATE(created_at) label,COUNT(*) value FROM orders WHERE created_at>=CURDATE()-INTERVAL 6 DAY GROUP BY DATE(created_at) ORDER BY label"));?></div><div class="col-md-6"><?php chart('Orders by barangay',rows('SELECT barangay label,COUNT(*) value FROM orders GROUP BY barangay'));?></div></div></div><div class="col-lg-4"><div class="card"><div class="card-body"><h3 class="section-title">Rider availability</h3><?php foreach(rows('SELECT u.name,r.availability FROM riders r JOIN users u ON u.id=r.user_id') as $r) echo '<div class="d-flex justify-content-between py-3 border-bottom">'.e($r['name']).'<span class="badge">'.e($r['availability']).'</span></div>';?></div></div><div class="card"><div class="card-body"><h3 class="section-title">Predicted refill customers</h3><?php $any=false;foreach(rows("SELECT id,name FROM users WHERE role='customer'") as $c){$p=prediction((int)$c['id']);if($p && $p['date']<=date('Y-m-d',strtotime('+2 days'))){$any=true;echo '<p>'.e($c['name']).'<br><span class="muted small">Estimated '.e($p['date']).'</span></p>';}}if(!$any)echo '<p class="muted">No upcoming refill estimates.</p>';?></div></div><div class="card"><div class="card-body"><h3 class="section-title">Today's delivery groups</h3><?php foreach(rows("SELECT barangay,COUNT(*) n,SUM(quantity) gallons FROM orders WHERE DATE(scheduled_at)=CURDATE() AND status<>'Cancelled' GROUP BY barangay") as $g)echo '<p>'.e($g['barangay']).' · '.$g['n'].' orders · '.$g['gallons'].' gallons</p>';?><a href="?page=deliveries">Open delivery groups →</a></div></div></div></div><?php
 echo '<div class="row"><div class="col-lg-4">';chart('Weekly orders',rows("SELECT DATE_FORMAT(created_at,'%x-W%v') label,COUNT(*) value FROM orders GROUP BY label ORDER BY label DESC LIMIT 8"));echo '</div><div class="col-lg-4">';chart('Monthly sales',rows("SELECT DATE_FORMAT(paid_at,'%Y-%m') label,SUM(amount) value FROM payments WHERE payment_status='Paid' GROUP BY label ORDER BY label DESC LIMIT 6"));echo '</div><div class="col-lg-4">';chart('Popular products',rows('SELECT p.name label,SUM(i.quantity) value FROM order_items i JOIN products p ON p.id=i.product_id JOIN orders o ON o.id=i.order_id WHERE o.status<>? GROUP BY p.id ORDER BY value DESC',['Cancelled']));echo '</div></div>';
 }else{echo '<h3 class="section-title">Your next deliveries</h3>';rider_cards(rows($orderSql." AND o.status IN ('Assigned','Out for Delivery') ORDER BY o.scheduled_at",$params)); rider_controls($u);}
}elseif(in_array($page,['orders','deliveries','completed'],true)){
 echo '<h1 class="h3 fw-bold mb-4">'.e($page==='completed'?'Completed deliveries':ucfirst($page)).'</h1>';
 $conditions='';$filterParams=$params;
 if($page==='completed')$conditions=" AND o.status='Delivered'";
 elseif($role==='rider')$conditions=" AND o.status IN ('Assigned','Out for Delivery')";
 if(!empty($_GET['date'])){$conditions.=' AND DATE(o.scheduled_at)=?';$filterParams[]=$_GET['date'];}
 if(!empty($_GET['barangay'])){$conditions.=' AND o.barangay=?';$filterParams[]=$_GET['barangay'];}
 if(!empty($_GET['status'])){$conditions.=' AND o.status=?';$filterParams[]=$_GET['status'];}
 ?><form class="row g-2 mb-4" method="get"><input type="hidden" name="page" value="<?=e($page)?>"><div class="col-sm-3"><input class="form-control" type="date" name="date" value="<?=e($_GET['date']??'')?>" aria-label="Delivery date"></div><div class="col-sm-3"><select name="barangay" class="form-select"><option value="">All barangays</option><?php foreach(rows('SELECT barangay FROM delivery_areas') as $a)echo '<option '.(($_GET['barangay']??'')===$a['barangay']?'selected':'').'>'.e($a['barangay']).'</option>';?></select></div><div class="col-sm-3"><select name="status" class="form-select"><option value="">All statuses</option><?php foreach(['Pending','Confirmed','Preparing','Assigned','Out for Delivery','Delivered','Cancelled'] as $s)echo '<option '.(($_GET['status']??'')===$s?'selected':'').'>'.e($s).'</option>';?></select></div><div class="col-sm-3"><button class="btn btn-primary">Filter</button></div></form><?php
 $os=rows($orderSql.$conditions.' ORDER BY o.scheduled_at DESC LIMIT 500',$filterParams);
 if($page==='deliveries' && $role==='admin'){ $groups=[];foreach($os as $o){if(in_array($o['status'],['Delivered','Cancelled'],true))continue;$key=$o['barangay'].' · '.date('M j, Y',strtotime($o['scheduled_at'])).' · '.(date('H',strtotime($o['scheduled_at']))<12?'Morning':'Afternoon');$groups[$key][]=$o;} foreach($groups as $label=>$group){echo '<h3 class="section-title">'.e($label).'</h3>';orders_table($group);$coords=array_values(array_filter($group,fn($o)=>$o['latitude']!==null && $o['longitude']!==null));if(count($coords)>1){$distance=haversine((float)$coords[0]['latitude'],(float)$coords[0]['longitude'],(float)$coords[1]['latitude'],(float)$coords[1]['longitude']);echo '<p class="muted small">First two points: '.round($distance,2).' km straight-line distance. Grouping does not optimize routes.</p>';}}if(!$groups)echo '<p class="muted">No active delivery groups.</p>';
 }elseif($role==='rider') rider_cards($os);else orders_table($os);
 if($role==='rider') rider_controls($u);
}elseif($page==='detail'){
 $o=one($orderSql.' AND o.id=?',array_merge($params,[$id]));if(!$o){echo '<div class="alert alert-warning">Order not found or access denied.</div>';end_page();exit;}
 $r=$o['rider_id']?one('SELECT u.name,u.phone,l.latitude,l.longitude,l.updated_at FROM users u LEFT JOIN rider_locations l ON l.rider_id=u.id WHERE u.id=?',[$o['rider_id']]):null;
 ?><div class="d-flex justify-content-between mb-4"><div><h1 class="h3 fw-bold"><?=e($o['order_number'])?></h1><span class="muted">Placed <?=e($o['created_at'])?></span></div><span class="badge align-self-start <?=e($o['status'])?>"><?=e($o['status'])?></span></div><div class="row"><div class="col-lg-8"><div class="card"><div class="card-body"><h3 class="section-title">Delivery details</h3><div class="row"><div class="col-md-6"><strong><?=e($o['customer_name'])?></strong><p><?=e($o['address'])?><br><?=e($o['barangay'])?><br><a href="tel:<?=e($o['customer_phone'])?>"><?=e($o['customer_phone'])?></a></p></div><div class="col-md-6"><p>Requested delivery<br><strong><?=e(date('F j, Y · g:i A',strtotime($o['scheduled_at'])))?></strong></p><p><?=e($o['quantity'])?> gallons · <?=money($o['gallon_price'])?> each<br>Delivery fee: <?=money($o['delivery_fee'])?></p></div></div><?php foreach(rows('SELECT p.name,i.quantity FROM order_items i JOIN products p ON p.id=i.product_id WHERE order_id=?',[$id]) as $item) echo '<p>'.e($item['name']).' × '.$item['quantity'].'</p>';?><hr><div class="d-flex justify-content-between"><strong>Order total</strong><strong><?=money($o['total'])?></strong></div></div></div><div class="card"><div class="card-body"><h3 class="section-title">Delivery tracking</h3><p><strong><?=$r?e($r['name']):'Waiting for rider assignment'?></strong><?=$r?' · <a href="tel:'.e($r['phone']).'">'.e($r['phone']).'</a>':''?></p><p class="muted">Current status: <?=e($o['status'])?>. Delivery time is requested and may change with station availability.</p><?php if($r && in_array($o['status'],['Assigned','Out for Delivery'],true) && $r['updated_at']):?><p class="small">Rider coordinates: <?=e($r['latitude'])?>, <?=e($r['longitude'])?><br>Last update: <?=e($r['updated_at'])?>. This location may be stale.</p><?php endif;?><div class="timeline"><?php foreach(rows('SELECT h.*,u.name FROM order_status_history h JOIN users u ON u.id=h.actor_id WHERE order_id=? ORDER BY h.id',[$id]) as $h) echo '<p><strong>'.e($h['note']?:$h['status']).'</strong><br><span class="muted small">'.e($h['created_at']).' · '.e($h['name']).'</span></p>';?></div><a href="?page=detail&id=<?=$id?>" class="btn btn-outline-info btn-sm">Refresh tracking</a></div></div></div><div class="col-lg-4"><div class="card"><div class="card-body"><h3 class="section-title">Payment</h3><p><?=e($o['payment_method'])?> <span class="badge <?=e($o['payment_status'])?>"><?=e($o['payment_status'])?></span></p><p class="small muted">Reference: <?=e($o['payment_reference']?:'Not provided')?></p><?php
 if($role==='customer' && $o['payment_method']!=='COD' && in_array($o['payment_status'],['Pending','Failed'],true)){echo '<p class="small">'.e(one('SELECT payment_instructions FROM water_stations WHERE id=1')['payment_instructions']).'</p>';form_start('reference',$id);field('reference','Transaction reference');form_end('Submit reference');}
 if($role==='admin'){form_start('payment',$id);select_field('payment_status','Manual payment verification',array_combine(['Pending','Paid','Failed','Refunded'],['Pending','Paid','Failed','Refunded']),$o['payment_status']);form_end('Update payment');if(in_array($o['status'],['Pending','Confirmed','Preparing','Assigned'],true)){echo '<hr>';form_start('schedule',$id);field('scheduled_at','Reschedule delivery','datetime-local',date('Y-m-d\TH:i',strtotime($o['scheduled_at'])));form_end('Save delivery schedule');}}
 ?></div></div><?php
 if($role==='customer'){echo '<div class="card"><div class="card-body">'; $item=one('SELECT product_id FROM order_items WHERE order_id=?',[$id]);echo '<a class="btn btn-primary mb-3" href="?page=order&reorder='.$id.'">Reorder water</a>';if($o['status']==='Pending'){form_start('cancel',$id,'Cancel this order?');form_end('Cancel order');}if($o['status']==='Delivered' && !one('SELECT id FROM feedback WHERE order_id=?',[$id])){echo '<h3 class="section-title mt-3">How was your delivery?</h3>';form_start('feedback',$id);select_field('rating','Rating',[5=>'5 — Excellent',4=>'4 — Good',3=>'3 — Okay',2=>'2 — Poor',1=>'1 — Very poor']);field('comment','Feedback','text','',false);form_end('Send feedback');}echo '</div></div>';}
 if(in_array($role,['admin','rider'],true)){echo '<div class="card"><div class="card-body"><h3 class="section-title">Delivery actions</h3>';if($role==='admin' && in_array($o['status'],['Confirmed','Preparing','Assigned'],true)){form_start('assign',$id);$options=[];foreach(rows("SELECT u.id,u.name,r.availability FROM users u JOIN riders r ON r.user_id=u.id WHERE r.availability<>'Offline'") as $rr)$options[$rr['id']]=$rr['name'].' · '.$rr['availability'];select_field('rider_id','Assign rider',$options,$o['rider_id']);form_end('Assign delivery');echo '<hr>';}$trans=['Pending'=>['Confirmed','Cancelled'],'Confirmed'=>['Preparing','Cancelled'],'Preparing'=>['Cancelled'],'Assigned'=>['Out for Delivery','Cancelled'],'Out for Delivery'=>['Delivered']];$states=$trans[$o['status']]??[];if($role==='rider'){$states=array_values(array_intersect($states,['Out for Delivery','Delivered']));if($o['status']==='Assigned'&&!$o['picked_up_at'])$states=['Picked Up'];}foreach($states as $s){form_start('status',$id,'Update order to '.$s.'?');echo '<input type="hidden" name="status" value="'.e($s).'">';form_end($s);echo '<div class="mb-2"></div>';}echo '</div></div>';}
 ?></div></div><?php
}elseif($page==='order' && $role==='customer'){
 $reorder=!empty($_GET['reorder'])?one('SELECT i.product_id,o.quantity FROM orders o JOIN order_items i ON i.order_id=o.id WHERE o.id=? AND o.customer_id=?',[(int)$_GET['reorder'],$u['id']]):null;
 $addresses=rows('SELECT a.*,d.fee FROM addresses a JOIN delivery_areas d ON d.barangay=a.barangay AND d.active=1 WHERE customer_id=?',[$u['id']]);
 echo '<h1 class="h3 fw-bold mb-4">Order your next refill</h1><div class="row">';foreach(rows('SELECT * FROM products WHERE active=1') as $p)echo '<div class="col-md-6 col-xl-4"><div class="card"><div class="card-body"><div class="product-art"><i class="bi bi-droplet-fill"></i></div><h3 class="h5 mt-3">'.e($p['name']).'</h3><p class="muted small">'.e($p['description']).'</p><strong>'.money($p['price']).' <span class="muted fw-normal small">/ gallon refill</span></strong></div></div></div>';echo '</div>';
 if(!$addresses) echo '<div class="alert alert-info">Add a delivery address before ordering. <a href="?page=addresses">Save an address →</a></div>';
 else{?><div class="card"><div class="card-body"><form id="order-form" method="post"><?=csrf()?><input type="hidden" name="action" value="order"><div class="row"><div class="col-md-6"><label class="form-label">Water product</label><select name="product_id" class="form-select mb-3"><?php foreach(rows('SELECT * FROM products WHERE active=1') as $p)echo '<option value="'.$p['id'].'" data-price="'.$p['price'].'" '.(($reorder['product_id']??0)==$p['id']?'selected':'').'>'.e($p['name']).' · '.money($p['price']).'</option>';?></select><?php field('quantity','Number of gallons','number',$reorder['quantity']??2);?><label class="form-label">Delivery address</label><select name="address_id" class="form-select mb-3"><?php foreach($addresses as $a)echo '<option value="'.$a['id'].'" data-fee="'.$a['fee'].'">'.e($a['address'].' · '.$a['barangay']).'</option>';?></select></div><div class="col-md-6"><?php field('scheduled_at','Requested delivery date / time','datetime-local',date('Y-m-d\T09:00',strtotime('+1 day')));select_field('payment_method','Payment method',['COD'=>'Cash on Delivery','GCash'=>'GCash · manually verified','Maya'=>'Maya · manually verified']);?><p class="muted small">GCash and Maya require a transaction reference and manual station verification. Delivery fees depend on your barangay.</p></div></div><div class="alert alert-info" id="order-review"></div><button class="btn btn-primary">Confirm order</button></form></div></div><?php }
}elseif($page==='addresses' && $role==='customer'){
 $edit=$id?one('SELECT * FROM addresses WHERE id=? AND customer_id=?',[$id,$u['id']]):null;
 echo '<h1 class="h3 fw-bold mb-4">Your delivery addresses</h1><div class="row"><div class="col-lg-7">';foreach(rows('SELECT * FROM addresses WHERE customer_id=?',[$u['id']]) as $a){echo '<div class="card"><div class="card-body"><i class="bi bi-geo-alt text-info me-2"></i><strong>'.e($a['barangay']).'</strong><p class="mt-2">'.e($a['address']).'</p><div class="d-flex gap-3 align-items-center"><a href="?page=addresses&id='.$a['id'].'">Edit address</a>';form_start('address_delete',(int)$a['id'],'Delete this saved address?');form_end('Delete');echo '</div></div></div>';}echo '</div><div class="col-lg-5"><div class="card"><div class="card-body"><h3 class="section-title">'.($edit?'Edit address':'Add an address').'</h3>';form_start('address',(int)($edit['id']??0));field('address','Street / house / landmark','text',$edit['address']??'');$opts=[];foreach(rows('SELECT barangay,fee FROM delivery_areas WHERE active=1') as $a)$opts[$a['barangay']]=$a['barangay'].' · '.money($a['fee']).' delivery';select_field('barangay','Barangay',$opts,$edit['barangay']??'');field('latitude','Latitude (optional)','number',$edit['latitude']??'',false);field('longitude','Longitude (optional)','number',$edit['longitude']??'',false);form_end('Save address');if($edit)echo '<a class="d-block mt-3" href="?page=addresses">Add a different address</a>';echo '</div></div></div></div>';
}elseif($page==='subscriptions' && in_array($role,['customer','admin'],true)){
 echo '<h1 class="h3 fw-bold mb-4">Recurring water deliveries</h1>';
 $subs=rows('SELECT s.*,p.name product,u.name customer,a.address,a.barangay FROM subscriptions s JOIN products p ON p.id=s.product_id JOIN users u ON u.id=s.customer_id JOIN addresses a ON a.id=s.address_id'.($role==='customer'?' WHERE s.customer_id=?':'').' ORDER BY s.next_delivery_date',$role==='customer'?[$u['id']]:[]);
 $dayNames=[1=>'Monday',2=>'Tuesday',3=>'Wednesday',4=>'Thursday',5=>'Friday',6=>'Saturday',7=>'Sunday'];echo '<div class="row"><div class="col-lg-7">';foreach($subs as $s){echo '<div class="card"><div class="card-body"><div class="d-flex justify-content-between"><h3 class="h5">'.e($s['product']).' · '.$s['quantity'].' gallons</h3><span class="badge">'.e($s['status']).'</span></div><p class="muted">'.e($s['customer']).' · '.e($s['barangay']).'<br>'.e(implode(' & ',array_map(fn($d)=>$dayNames[(int)$d],explode(',',$s['selected_days'])))).' at '.e(substr($s['preferred_time'],0,5)).'<br>Next delivery: '.e($s['next_delivery_date']).' · '.e($s['payment_method']).'</p>';if($role==='customer'&&$s['status']!=='Cancelled'){echo '<div class="d-flex gap-2">';foreach([$s['status']==='Active'?'Paused':'Active','Cancelled'] as $state){form_start('subscription_status',(int)$s['id'],'Change subscription to '.$state.'?');echo '<input type="hidden" name="status" value="'.$state.'">';form_end($state==='Active'?'Resume':($state==='Paused'?'Pause':'Cancel'));}echo '</div><p class="small muted mt-3 mb-0">Pausing or cancelling stops future generation. Existing orders remain in your order history.</p>';}echo '</div></div>';}if(!$subs)echo '<p class="muted">No subscriptions yet.</p>';echo '</div>';
 if($role==='customer'){echo '<div class="col-lg-5"><div class="card"><div class="card-body"><h3 class="section-title">Create a schedule</h3>';form_start('subscription');$opts=[];foreach(rows('SELECT * FROM products WHERE active=1') as $p)$opts[$p['id']]=$p['name'].' · '.money($p['price']);select_field('product_id','Product',$opts);field('quantity','Gallons per delivery','number',2);$opts=[];foreach(rows('SELECT a.* FROM addresses a JOIN delivery_areas d ON d.barangay=a.barangay AND d.active=1 WHERE customer_id=?',[$u['id']]) as $a)$opts[$a['id']]=$a['address'].' · '.$a['barangay'];select_field('address_id','Address',$opts);echo '<label class="form-label">Weekly delivery days</label><div class="mb-3">';foreach($dayNames as $num=>$name)echo '<label class="me-3 mb-2 small"><input type="checkbox" name="days[]" value="'.$num.'"> '.$name.'</label>';echo '</div>';field('preferred_time','Preferred time','time','09:00');field('start_date','Start date','date',date('Y-m-d'));select_field('payment_method','Payment method',['COD'=>'COD','GCash'=>'GCash','Maya'=>'Maya']);form_end('Create subscription');echo '</div></div></div>';}echo '</div>';
}elseif($page==='notifications'){
 echo '<div class="d-flex justify-content-between mb-4"><h1 class="h3 fw-bold">Notifications</h1>';form_start('read');form_end('Mark all as read');echo '</div>';foreach(rows('SELECT * FROM notifications WHERE user_id=? ORDER BY id DESC LIMIT 200',[$u['id']]) as $n)echo '<div class="card"><div class="card-body"><i class="bi bi-bell text-info me-2"></i>'.e($n['message']).($n['read_at']?'':' <span class="badge">New</span>').'<div class="muted small mt-2">'.e($n['created_at']).'</div></div></div>';
}elseif(in_array($page,['profile','settings'],true)){
 echo '<h1 class="h3 fw-bold mb-4">'.($page==='settings'?'Station & account settings':'Your profile').'</h1><div class="row"><div class="col-lg-6"><div class="card"><div class="card-body"><h3 class="section-title">Account details</h3>';form_start('profile');field('name','Full name','text',$u['name']);field('phone','Contact number','tel',$u['phone']);echo '<p class="muted">'.e($u['email']).'</p>';field('current_password','Current password (to change password)','password','',false);field('password','New password (at least 10 characters)','password','',false);form_end();echo '</div></div></div>';
 if($role==='admin' && $page==='settings'){$s=one('SELECT * FROM water_stations WHERE id=1');echo '<div class="col-lg-6"><div class="card"><div class="card-body"><h3 class="section-title">Station profile</h3>';form_start('station');field('name','Station name','text',$s['name']);field('address','Station address','text',$s['address']);field('phone','Contact number','tel',$s['phone']);field('payment_instructions','Verified payment instructions','text',$s['payment_instructions']);form_end();echo '</div></div></div>';}echo '</div>';
}elseif($role==='admin' && in_array($page,['products','areas'],true)){
 $product=$page==='products';echo '<h1 class="h3 fw-bold mb-4">'.($product?'Water products':'Delivery areas').'</h1><div class="row">';$items=rows('SELECT * FROM '.($product?'products':'delivery_areas').' ORDER BY id');$items[]=['id'=>0,'name'=>'','description'=>'','price'=>'','barangay'=>'','fee'=>'','active'=>1];foreach($items as $item){echo '<div class="col-md-6 col-xl-4"><div class="card"><div class="card-body"><h3 class="section-title">'.($item['id']?'Edit '.e($product?$item['name']:$item['barangay']):'Add '.($product?'product':'area')).'</h3>';form_start($product?'product':'area',(int)$item['id']);if($product){field('name','Product name','text',$item['name']);field('description','Description','text',$item['description'],false);field('price','Gallon price (₱)','number',$item['price']);}else{field('barangay','Barangay','text',$item['barangay']);field('fee','Delivery fee (₱)','number',$item['fee']);}echo '<label class="mb-3"><input type="checkbox" name="active" '.($item['active']?'checked':'').'> Available</label><br>';form_end($item['id']?'Save changes':'Add');echo '</div></div></div>';}echo '</div><p class="muted small">Disable a product or area to remove it from new orders while preserving historical records.</p>';
}elseif($role==='admin' && $page==='riders'){
 echo '<h1 class="h3 fw-bold mb-4">Your delivery team</h1><div class="row"><div class="col-lg-7">';foreach(rows('SELECT u.*,r.availability,l.latitude,l.longitude,l.updated_at location_time FROM users u JOIN riders r ON r.user_id=u.id LEFT JOIN rider_locations l ON l.rider_id=u.id') as $r)echo '<div class="card"><div class="card-body"><h3 class="h5">'.e($r['name']).' <span class="badge">'.e($r['availability']).'</span></h3><p>'.e($r['email']).' · '.e($r['phone']).'</p><p class="muted small mb-0">Last location: '.e($r['latitude']??'Unavailable').', '.e($r['longitude']??'Unavailable').' · '.e($r['location_time']??'No update').'</p></div></div>';echo '</div><div class="col-lg-5"><div class="card"><div class="card-body"><h3 class="section-title">Add a rider</h3>';form_start('rider');field('name','Full name');field('email','Email','email');field('phone','Contact number','tel');field('password','Initial password (at least 10 characters)','password');form_end('Create rider account');echo '</div></div></div></div>';
}elseif($role==='admin' && $page==='customers'){
 echo '<h1 class="h3 fw-bold mb-4">Customers & refill estimates</h1>';if($id){$c=one("SELECT id,name,email,phone FROM users WHERE role='customer' AND id=?",[$id]);if($c){echo '<h3 class="section-title">'.e($c['name']).' · '.e($c['phone']).'</h3>';orders_table(rows($orderSql.' AND o.customer_id=? ORDER BY o.created_at DESC',[$id]));}}else{echo '<div class="card"><div class="table-responsive"><table class="table"><thead><tr><th>Customer</th><th>Contact</th><th>Orders</th><th>Estimated refill</th></tr></thead><tbody>';foreach(rows("SELECT u.id,u.name,u.email,u.phone,COUNT(o.id) n FROM users u LEFT JOIN orders o ON o.customer_id=u.id WHERE u.role='customer' GROUP BY u.id") as $c){$p=prediction((int)$c['id']);echo '<tr><td><a href="?page=customers&id='.$c['id'].'">'.e($c['name']).'</a></td><td>'.e($c['email']).'<br>'.e($c['phone']).'</td><td>'.$c['n'].'</td><td>'.e($p['date']??'Insufficient history').'</td></tr>';}echo '</tbody></table></div></div>';}
}elseif($role==='admin' && $page==='feedback'){
 echo '<h1 class="h3 fw-bold mb-4">Customer feedback</h1>';foreach(rows('SELECT f.*,u.name,o.order_number FROM feedback f JOIN users u ON u.id=f.customer_id JOIN orders o ON o.id=f.order_id ORDER BY f.id DESC') as $f)echo '<div class="card"><div class="card-body"><span class="text-warning">'.str_repeat('★',(int)$f['rating']).'</span><h3 class="h5 mt-2">'.e($f['name']).' · '.e($f['order_number']).'</h3><p>'.e($f['comment']).'</p><span class="muted small">'.e($f['created_at']).'</span></div></div>';
}elseif($role==='admin' && $page==='reports'){
 $start=$_GET['start']??date('Y-m-01');$end=$_GET['end']??date('Y-m-d');$where='DATE(o.created_at) BETWEEN ? AND ?';$rp=[$start,$end];if(!empty($_GET['barangay'])){$where.=' AND o.barangay=?';$rp[]=$_GET['barangay'];}if(!empty($_GET['status'])){$where.=' AND o.status=?';$rp[]=$_GET['status'];}
 ?><h1 class="h3 fw-bold mb-4">Station reports</h1><form class="row g-2 mb-4"><input type="hidden" name="page" value="reports"><div class="col-md-3"><?php field('start','Start date','date',$start);?></div><div class="col-md-3"><?php field('end','End date','date',$end);?></div><div class="col-md-2"><?php field('barangay','Barangay','text',$_GET['barangay']??'',false);?></div><div class="col-md-2"><?php select_field('status','Status',[''=>'All','Pending'=>'Pending','Confirmed'=>'Confirmed','Preparing'=>'Preparing','Assigned'=>'Assigned','Out for Delivery'=>'Out for Delivery','Delivered'=>'Delivered','Cancelled'=>'Cancelled'],$_GET['status']??'');?></div><div class="col-md-2 align-self-center"><button class="btn btn-primary">Apply filters</button></div></form><?php
 $reportOrders=rows('SELECT o.*,u.name customer_name,p.payment_status FROM orders o JOIN users u ON u.id=o.customer_id JOIN payments p ON p.order_id=o.id WHERE '.$where.' ORDER BY o.created_at DESC',$rp);$paid=0;$completed=0;$cancelled=0;foreach($reportOrders as $ro){if($ro['payment_status']==='Paid')$paid+=(float)$ro['total'];$completed+=$ro['status']==='Delivered';$cancelled+=$ro['status']==='Cancelled';}echo '<div class="row">';stat_card('Orders',count($reportOrders),'bag');stat_card('Paid revenue',money($paid),'cash');stat_card('Completed deliveries',$completed,'check-circle');stat_card('Cancelled orders',$cancelled,'x-circle');echo '</div><p class="muted small">Filters use order creation date. Revenue includes payments currently marked Paid for the selected orders.</p><div class="row">';
 foreach(['Daily orders'=>'DATE(o.created_at)','Weekly orders'=>'DATE_FORMAT(o.created_at,\'%x-W%v\')','Monthly orders'=>'DATE_FORMAT(o.created_at,\'%Y-%m\')','Orders per barangay'=>'o.barangay'] as $title=>$expr){echo '<div class="col-lg-6">';chart($title,rows('SELECT '.$expr.' label,COUNT(*) value FROM orders o WHERE '.$where.' GROUP BY label ORDER BY label',$rp));echo '</div>';}
 echo '<div class="col-lg-6">';chart('Monthly sales (paid)',rows("SELECT DATE_FORMAT(o.created_at,'%Y-%m') label,SUM(p.amount) value FROM orders o JOIN payments p ON p.order_id=o.id WHERE $where AND p.payment_status='Paid' GROUP BY label ORDER BY label",$rp));echo '</div><div class="col-lg-6">';chart('Popular products (gallons)',rows('SELECT p.name label,SUM(i.quantity) value FROM orders o JOIN order_items i ON i.order_id=o.id JOIN products p ON p.id=i.product_id WHERE '.$where.' GROUP BY p.id ORDER BY value DESC',$rp));echo '</div><div class="col-lg-6">';chart('Customer order frequency',rows('SELECT u.name label,COUNT(*) value FROM orders o JOIN users u ON u.id=o.customer_id WHERE '.$where.' GROUP BY u.id ORDER BY value DESC LIMIT 20',$rp));echo '</div></div>';orders_table($reportOrders);
}else{http_response_code(404);echo '<div class="alert alert-warning">Page not found.</div>';}
end_page();
function rider_controls(array $u): void { echo '<div class="card"><div class="card-body"><h3 class="section-title">Availability & location</h3>';form_start('availability');select_field('availability','Your availability',['Available'=>'Available','Busy'=>'Busy','Offline'=>'Offline'],one('SELECT availability FROM riders WHERE user_id=?',[$u['id']])['availability']);form_end('Update availability');echo '<button type="button" class="btn btn-outline-info mt-3" id="share-location"><i class="bi bi-geo-alt me-2"></i>Update current location</button><p class="muted small mt-2" id="location-result">Location sharing requires browser permission and an active delivery. Use HTTPS or localhost.</p></div></div>'; }

